project:
  type: book
  output-dir: docs

book:
  title: "rtools-qbook"
  author: "Collin Edwards"
  date: "7/10/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - dataprocessing.qmd
    - communication.qmd
    - figure_cookbook.qmd
    - dev_and_simulations.qmd
    - framverse.qmd
    - other_resources.qmd
    - interactive_interfaces.qmd
    - package_stubs.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    embed-resources: true
  pdf:
    documentclass: scrreprt

standalone: true
editor: visual
